"""user: add some fields

Revision ID: 3aa456f5b43e
Revises: 9c5e7c94e3d7
Create Date: 2024-07-30 17:00:45.513598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa456f5b43e'
down_revision = '9c5e7c94e3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dev', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('is_dev')

    # ### end Alembic commands ###
