"""Initial migration.

Revision ID: 8645edaac494
Revises: 
Create Date: 2024-06-28 21:02:44.751723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8645edaac494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('maps_id', sa.String(length=1000), nullable=True),
    sa.Column('taste_biography', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), unique=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('is_admin', sa.Boolean()),
    sa.Column('taste_biography', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')

    op.drop_table('restaurant')
    # ### end Alembic commands ###
