"""restaurant: add more fields

Revision ID: 9c5e7c94e3d7
Revises: 9d00a35289c3
Create Date: 2024-07-29 20:00:33.861574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5e7c94e3d7'
down_revision = '9d00a35289c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_amount', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('maps_id',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('taste_biography',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('taste_biography',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
        batch_op.alter_column('maps_id',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.drop_column('review_amount')
        batch_op.drop_column('rating')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('is_test')

    # ### end Alembic commands ###
