"""Create DeleteFeedback

Revision ID: badebd87bdc0
Revises: 2d7d338fce25
Create Date: 2024-08-11 17:50:02.635116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badebd87bdc0'
down_revision = '2d7d338fce25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delete_feedback')
    # ### end Alembic commands ###
